### ISSUE TITLE
Can't invoke Mrspec with line numbers

### ISSUE THREAD

**Issue by joallard** [JoshCheek/mrspec#21]
Running `mrspec test/lib/test_file.rb:30` runs the whole file.

Not sure if this is supposed to work, if not, how hard would it be to implement?

**Comment by JoshCheek** [comment]
Can you include an example? It's working for me:

Dir structure:

```sh
$ tree
.
└── test
    └── lib
        └── test_file.rb

2 directories, 1 file
```

The file:

```sh
$ cat test/lib/test_file.rb | ruby -pe 'print $., ?\t'
1	RSpec.describe do
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29	  example('twenty nine') { }
30	  example('thirty')      { }
31	  example('thirty one')  { }
32	end
```

Running it:

```sh
$ mrspec -f d test/lib/test_file.rb:30
Run options: include {:locations=>{"./test/lib/test_file.rb"=>[30]}}


  thirty

Finished in 0.0007 seconds (files took 0.12208 seconds to load)
1 example, 0 failures
```

Version

```sh
$ mrspec -v
mrspec     0.3.1
rspec-core 3.5.4
minitest   5.10.1
wwhhiae2c  0.0.8
```

**Comment by joallard** [comment]
I'm not able to put together a repro case. So I spent a few hours Pry'ing.

Given I have `it`s on lines 13 and 21.

* `RSpec::Core::FilterManager#prune` is not pruning example on 21
*  `RSpec::Core::FilterManager#file_scoped_include?` runs 

```
        no_location_filters = locations[
          File.expand_path(ex_metadata[:rerun_file_path])
        ].empty?
```

and finds `true` because `ex_metadata[:rerun_file_path] == ".../mrspec-0.3.1/lib/mrspec/declare_minitests.rb"` and `inclusions` doesn't have a line number for that file.

I assumed this was the wrong file, and needed the test source file to be at `:rerun_file_path` even though I don't know what it means.

In `Metadata`, `:rerun_file_path` is populated with the calling block location, which is `#<Proc:0x007ff32f880f70@.../mrspec-0.3.1/lib/mrspec/declare_minitests.rb:50>`

And finally:

```
From: /Users/jon/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/mrspec-0.3.1/lib/mrspec/declare_minitests.rb @ line 50 MRspec::DeclareMinitests#wrap_test:

    48: def wrap_test(example_group, klass, mname)
    49:   metadata = klass.example_metadata[mname.intern]
 => 50:   example  = example_group.example example_name(mname), metadata do
    51:     instance = Minitest.run_one_method klass, mname
    52:     next              if instance.passed?
    53:     pending 'skipped' if instance.skipped?
    54:     error = instance.failure.error
    55:     raise error unless error.kind_of? Minitest::Assertion
    56:     raise MinitestAssertionForRSpec.new error
    57:   end
    58:   fix_metadata example.metadata, klass.instance_method(mname)
    59: end
```

But wait, `metadata` is empty. And then, hi, there's `fix_metadata` there.

```
[89] pry(MRspec::DeclareMinitests)> klass.instance_method(mname).source_location
=> [".../test/lib/x_test.rb", 21]
```

So the result works, does the setting work?

```
def fix_metadata(metadata, method)
  file, line = method.source_location
  return unless file && line # not sure when this wouldn't be true, so no tests on it, but hypothetically it could happen
  metadata[:file_path]          = file
  metadata[:line_number]        = line
  metadata[:location]           = "#{file}:#{line}"
  metadata[:absolute_file_path] = File.expand_path(file)
end
```

I don't see a `rerun_file_path` in there, is that normal?

And just for info, the file structure I'm operating on looks like:

```
class XTest < ActiveSupport::TestCase
  include ActiveJob::TestHelper

  describe "ModelExtension" do
    let(:foo){ FactoryGirl.create :foo }

    describe "#as_bar" do
      it "returns foobar" do
```

(not that it was my decision)

**Comment by JoshCheek** [comment]
Okay, got it figured out. Tried to record it @ https://www.liveedu.tv/joshcheek/videos/Mpkyn but the audio got fucked. Might be interesting anyway, IDK. Anyway, you were right on top of it.

We can reproduce it like this:

```ruby
require 'minitest/spec'
class T < Minitest::Spec
  describe "group" do
    it "e1" do
      assert_equal true, false
    end
    it "e2" do
      assert_equal true, false
    end
  end
end
```

Once I had that, I walked through the code, prob a lot of the same stuff that you did when you went through it in pry. In the end, you were right where I wound up. The `fix_metadata` method isn't setting the `rerun_file_path` key, and so they pull the value from the backtrace and find the mrspec file.

We could add more stuff to the metadata, but TBH, this is kind of iffy, IIRC, that key may not be so straightforward, eg values declared in a loop get more sophisticated rerun info. So it's best to let RSpec figure out what it should be.

While looking at it, I found that we can pass the backtrace that we want it to use to infer the file path. Then we can give it a backtrace that doesn't involve mrspec files. I just hacked it into place from pry and it looked like this:

```ruby
# https://github.com/JoshCheek/mrspec/blob/278f0489119ebb31466750a91bd4412374654026/lib/mrspec/declare_minitests.rb#L41

def wrap_class(rspec, klass)
  injected_metadata = {}
  runnables         = klass.runnable_methods
  if runnables.any?
    mrspec_path = File.expand_path(__dir__)
    caller_without_mrspec = caller.reject { |line| line[mrspec_path] }
    fake_caller = [*klass.instance_method(runnables.first).source_location.join(":"),
                   *caller_without_mrspec]
    injected_metadata[:caller] = fake_caller
  end
  example_group = rspec.describe group_name(klass), klass.class_metadata, **injected_metadata
  klass.runnable_methods.each do |method_name|
    wrap_test example_group, klass, method_name
  end
end
```

That code isn't fit for much, but it shows how to wire them together to fix the issue.

**Comment by joallard** [comment]
I haven't looked at the implementation closely, but I can confirm that it works! And yes, indeed, that metadata populator in Rspec accepts a backtrace.

Is this something you're planning of integrating into mainline or just a one-off fix?

**Comment by JoshCheek** [comment]
Fixed it and pushed it as 0.3.2

Had to bump the dependency on RSpec since they changed some internals that MRSpec knows too much about.

**Comment by joallard** [comment]
Amazing maintenance support @JoshCheek, thanks so much!

**Comment by joallard** [comment]
@JoshCheek Not sure if that's in scope, but I'm getting some weird metadata and line invocations failing with `minitest-spec-rails`.

Instead of the right metadata, at the end of the test it reports stuff like:

```
minitest-spec-rails-5.4.0/lib/minitest-spec-rails/dsl.rb[1:4]
```

Any pointers on where I can look to make this easier to solve?

**Comment by JoshCheek** [comment]
Hey, sry, I really do very little Rails these days (I haven't worked in ~8 moths, and I haven't done Rails in ~2 years). Doesn't mean I'm not willing to offer suggestions or dig into it, just that I need a bit more hand-holding. Eg some code that reproduces the issue. I know this isn't ideal, but based on the work I've done on [Seeing is Believing](https://github.com/JoshCheek/seeing_is_believing), having someone involved in a project who eats their own dogfood is incredibly valuable. Since that's not my situation, you're likely to hit a lot of issues w/ the lib that I'd ideally hit and fix before you. If this is too much work, then I get that, there's a ton of hacks in here to get this code to work, and it probably deserves more active attention than I put in :/

I will say that if it's a metadata issue then it's likely where I updated the code, so that's a good place to jump in and look around, just making sure things appear sane.

Additionally, since this is a backtrace issue, you can pass the `-b` flag to tell it to not filter the backtrace. Since rspec and mrspec both try to filter the backtrace to just show the relevant pieces, either of these could be causing isssues.

**Comment by joallard** [comment]
I totally understand what you mean, greatly put. I suffer from the same issue on a few projects.

Thanks for the follow up, I'll try to see what I can find out!
